# Senhas de administrador e padrão
SENHA_ADMIN = "NMQ@2025"
SENHA_PADRAO = "NMQ@123"

# Suas credenciais do Google
[gcp_service_account]
type = "service_account"
project_id = "..."
private_key_id = "..."
private_key = "..."
client_email = "..."
client_id = "..."
auth_uri = "..."
token_uri = "..."
auth_provider_x509_cert_url = "..."
client_x509_cert_url = "..."
